Deb/slack to google sheets write sheets
NUTFes/nutmeg-slack pull request #60
Opened 2023-06-25 10:32 UTC by YosukeIida

# 概要
botをメンション + テキストで，テキストをスプレッドシートに記入する

# 内容
main.pyにbotをメンションで動作する部分を追加した

# 画面スクリーンショット
![image](https://github.com/NUTFes/nutmeg-slack/assets/95607264/199aaff0-241e-4621-ae5a-fa96191bf32a)
![image](https://github.com/NUTFes/nutmeg-slack/assets/95607264/b16c42b7-0dd7-439f-985b-39512fd48454)

# テスト項目
- [ ] スプレッドシートに追加されているか確認
-  slackチャンネルで，botをメンション + テキスト を送信して，スプレッドシートに "日付, 表示名，テキスト" がシートの最後の行に追加されているか
- スプレッドシートに追加されている項目が1つかどうか
- [ ] slackのチャンネルに，メッセージとスプレッドシートURLが送信されているか

2023-06-25 15:06 UTC, ryuseifujisaki requested changes
とりあえず、レビューしました！
修正お願いします。:🙇

2023-06-25 15:06 UTC, ryuseifujisaki commented on slackbot/requirements.txt
> +re
```suggestion
```
余分なimportでbuildできないようになっているので削除してください:🙇

2023-06-25 15:06 UTC, ryuseifujisaki commented on slackbot/main.py
> +import logging
```suggestion
```
使用していないimportは削除しましょう

2023-06-25 15:06 UTC, ryuseifujisaki commented on slackbot/main.py
> +from slack_sdk import WebClient
```suggestion
```
これも使用してなさそうですね

2023-06-25 15:06 UTC, ryuseifujisaki commented on slackbot/main.py
> +#   ack()
```suggestion
```
不要なコメントアウトは削除しましょう!

2023-06-25 15:06 UTC, ryuseifujisaki commented on slackbot/main.py
> +  print(last_row_index, insert_text)
```suggestion
```
デバッグも基本的に開発し終わったら削除するのが良さです

2023-06-25 15:06 UTC, ryuseifujisaki commented on slackbot/main.py
> +  ]
```suggestion
```
利用していない関数は削除しましょう

2023-06-25 15:06 UTC, ryuseifujisaki commented on slackbot/main.py
> +# worksheet.update_cell(1, 2, export_value)
```suggestion
```
不必要なコメントアウトは消しましょう！

2023-06-25 15:06 UTC, ryuseifujisaki commented on slackbot/main.py
> +# リスナーのログと同時に見るためにペイロードを標準出力に表示するだけの middleware です
```suggestion
```
不必要なコメントアウトは削除しましょう！

2023-06-25 15:06 UTC, ryuseifujisaki commented on slackbot/main.py
> +  # print(replace_user_dict)
```suggestion
```
不必要なコメントアウト

2023-06-25 15:06 UTC, ryuseifujisaki commented on slackbot/main.py
> +  print(f"メンションされました:{text}")
```suggestion
```
デバッグは削除

2023-06-25 15:06 UTC, ryuseifujisaki commented on slackbot/main.py
> +    # say(','.join(insert_text))
```suggestion
```
コメントアウトは削除

2023-06-25 15:13 UTC, ryuseifujisaki commented
全体的に不要なコメントアウト、print文によるデバッグが残ってます！
チーム開発やプログラミング開発においてはこのようなものは消しておくとgoodです！
コメントアウト・print文を削除することで、以下のメリットがあります。
- 可読性の向上
- git管理を行いやすくする

2023-06-28 07:05 UTC, YosukeIida commented
修正しました．
よろしくお願いします．

2023-06-28 07:34 UTC, ryuseifujisaki requested changes

2023-06-28 07:34 UTC, ryuseifujisaki commented on slackbot/Dockerfile
> +RUN pip install oauth2client
requirement.txtに入れるとよさ

2023-06-28 07:34 UTC, ryuseifujisaki commented on slackbot/main.py
> +def handle_mentions(ack, context, body, say, logger, request):
```suggestion
def handle_mentions(body, say):
```
利用していない引数の削除

2023-06-28 07:34 UTC, ryuseifujisaki commented on slackbot/main.py
> +  sent_user_name = replace_user_dict.get(user)git
```suggestion
  sent_user_name = replace_user_dict.get(user)
```
`git`の削除

2023-06-28 07:34 UTC, ryuseifujisaki commented on slackbot/main.py
> +
```suggestion
```
謎のスペースの削除

2023-06-28 07:34 UTC, ryuseifujisaki commented on slackbot/main.py
> +
```suggestion
```
改行の削除

2023-06-28 07:34 UTC, ryuseifujisaki commented on slackbot/main.py
> +
```suggestion
```
改行の削除

2023-06-28 07:34 UTC, ryuseifujisaki commented on slackbot/main.py
> +  if not insert_text in worksheet.get_all_values():
```suggestion
  if insert_text in worksheet.get_all_values() == False:
```
`if not`はあまり利用しない方がいいかなと思います。

2023-06-28 07:34 UTC, ryuseifujisaki commented on slackbot/main.py
> +
```suggestion
```
不要な差分

2023-06-28 07:56 UTC, ryuseifujisaki requested changes

2023-06-28 07:56 UTC, ryuseifujisaki commented on slackbot/main.py
> +from template import modal
```suggestion
```

2023-06-28 07:56 UTC, ryuseifujisaki commented on slackbot/main.py
> +from typing import Callable, Dict, List
```suggestion
```

2023-06-28 07:56 UTC, ryuseifujisaki commented on slackbot/main.py
> +from slack_bolt import App, Ack, BoltResponse, BoltContext, Respond, Say
```suggestion
from slack_bolt import App
```

2023-06-28 07:56 UTC, ryuseifujisaki commented on slackbot/main.py
> +SPREADSHEET_KEY = '1eu6g0o5bVSAOexjC5COzgZaqjzGSJVqrtyousFv8KCc'
```suggestion
SPREADSHEET_KEY = os.environ("SPREADSHEET_KEY")
```

2023-06-28 07:56 UTC, ryuseifujisaki commented on slackbot/main.py
> +SPREADSHEET_KEY = '1eu6g0o5bVSAOexjC5COzgZaqjzGSJVqrtyousFv8KCc'
環境変数に入れるとよさ

2023-06-28 07:56 UTC, ryuseifujisaki commented on slackbot/main.py
> +  channel = mention["channel"]
```suggestion
```
使用していなさそうなので削除

2023-06-28 08:35 UTC, ryuseifujisaki commented on slackbot/main.py
> +  date_string = date_with_microseconds.strftime('%Y/%m/%d %H:%M:%S')
```suggestion
def convert_unixtime()
  # Unix時刻を秒とマイクロ秒に分割
  seconds = int(float(thread_ts))
  microseconds = int((float(thread_ts) - seconds) * 1000000)

  # Unixエポック時間を日付に変換
  date = datetime.datetime.fromtimestamp(seconds) + datetime.timedelta(hours=9)

  # マイクロ秒を追加
  date_with_microseconds = date + datetime.timedelta(microseconds=microseconds)

  # 日付を文字列に変換
  date_string = date_with_microseconds.strftime('%Y/%m/%d %H:%M:%S')
```
将来的にメソッドにすると良さそう

2023-06-28 08:37 UTC, merged